# Generates tools/kiosk_bar/kiosk_icons.h: 48x48 RGBA mini versions of the
# drawer app icons that can run inside the Chromium kiosk session.
Add-Type -AssemblyName System.Drawing

$repo = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$out = Join-Path $repo "tools\kiosk_bar\kiosk_icons.h"
$size = 48

# name-in-apps-file -> drawer png (only chromium-capable apps)
$icons = [ordered]@{
    "chromium"  = "chromium.png"
    "youtube"   = "youtube.png"
    "github"    = "github.png"
    "facebook"  = "facebook.png"
    "messenger" = "messenger.png"
    "teams"     = "team.png"
    "studio"    = "studio.png"
    "chatgpt"   = "chat-gpt.png"
    "pods"      = "pods.png"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by tools/kiosk_bar/gen_kiosk_icons.ps1 -- do not edit by hand.")
[void]$sb.AppendLine(" * ${size}x${size} straight (non-premultiplied) RGBA mini renders of the drawer")
[void]$sb.AppendLine(" * icons for the apps the Chromium kiosk launcher can open. kiosk_bar.c")
[void]$sb.AppendLine(" * blends them over its black island/menu surfaces at draw time. */")
[void]$sb.AppendLine("#ifndef KIOSK_ICONS_H")
[void]$sb.AppendLine("#define KIOSK_ICONS_H")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#define KIOSK_ICON_PX $size")
[void]$sb.AppendLine("")

$names = @()
foreach ($entry in $icons.GetEnumerator()) {
    $name = $entry.Key
    $png = Join-Path $repo ("assets\icons\drawer\" + $entry.Value)
    if (-not (Test-Path $png)) { Write-Error "missing $png"; exit 1 }
    $src = [System.Drawing.Image]::FromFile($png)
    $bmp = New-Object System.Drawing.Bitmap -ArgumentList $size, $size, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    $g.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
    # aspect-fit into the square, centered
    $scale = [Math]::Min($size / $src.Width, $size / $src.Height)
    $w = [int][Math]::Round($src.Width * $scale)
    $h = [int][Math]::Round($src.Height * $scale)
    $x = [int](($size - $w) / 2)
    $y = [int](($size - $h) / 2)
    $g.DrawImage($src, $x, $y, $w, $h)
    $g.Dispose()
    $src.Dispose()

    $rect = New-Object System.Drawing.Rectangle 0, 0, $size, $size
    $data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
                          [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $bytes = New-Object byte[] ($size * $size * 4)
    [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $bytes.Length)
    $bmp.UnlockBits($data)
    $bmp.Dispose()

    [void]$sb.AppendLine("static const unsigned char kiosk_icon_$name[$size * $size * 4] = {")
    $line = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $size * $size; $i++) {
        # BGRA (little-endian ARGB) -> RGBA
        $b = $bytes[$i * 4]; $gr = $bytes[$i * 4 + 1]; $r = $bytes[$i * 4 + 2]; $a = $bytes[$i * 4 + 3]
        [void]$line.Append("$r,$gr,$b,$a,")
        if (($i % 12) -eq 11) {
            [void]$sb.AppendLine($line.ToString())
            [void]$line.Clear()
        }
    }
    if ($line.Length -gt 0) { [void]$sb.AppendLine($line.ToString()) }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    $names += $name
}

[void]$sb.AppendLine("static const struct kiosk_icon {")
[void]$sb.AppendLine("    const char *name;               /* matched against app name and URL */")
[void]$sb.AppendLine("    const unsigned char *rgba;      /* KIOSK_ICON_PX^2 straight RGBA */")
[void]$sb.AppendLine("} kiosk_icons[] = {")
foreach ($name in $names) {
    [void]$sb.AppendLine("    {`"$name`", kiosk_icon_$name},")
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif /* KIOSK_ICONS_H */")

[System.IO.File]::WriteAllText($out, $sb.ToString())
Write-Output "wrote $out"
